project:
  type: website
  execute-dir: project
  output-dir: docs
  # render:
  #   - "*.qmd"
  # 
editor: source
execute:
  echo: false
warning: false



website:
  title: "Data Lab GitHub"
  navbar:
    right:

      - href: index.qmd
        text: "Home"

      - text: "Reports"
        href: DAC_Report.qmd

      - icon: github
        href: https://github.com/caids-datalab

format: 
  #pdf: default
  # docx:
  #   reference-doc: custom-reference-doc.docx
  #   number-sections: true
  #   citation-package: biblatex
  #   output-file: "DAC_Report_Spring2024"
  html:
    toc: false
    toc-location: left
    toc-depth: 2
    number-sections: true
    number-depth: 1
    theme: lumen
    highlight-style: github
    code-overflow: wrap
    code-fold: false
    code-copy: true
    code-link: false
    code-tools: false
    code-block-border-left: "#0C3823"
    code-block-bg: "#eeeeee"
    fig-cap-location: bottom
    linestretch: 1.25
    fontsize: "large"
    fontfamily: roboto
    embed-resources: true
css: styles.css



