---
title: "Welcome to the Data Lab's GitHub"
subtitle: "Connolly Alexander Institute for Data Science (CAIDS)!"
title-block-banner: "#285C4D"
title-block-banner-color: "#ffffff"
---

At [CAIDS](https://datainstitute.tulane.edu/), we empower undergraduate and graduate students to shape the data literacy landscape at Tulane University and beyond. Our mission is to build interdisciplinary and equity-minded data communities through collaboration and mutual support.


Through our [GitHub repositories](https://github.com/caids-datalab) and pages we share code and resources produced by participants in our programs. Feel free to put in a pull request and contribute.


## Our Programs

### 1. Student Scholarships
- **Objective:** Foster supportive interdisciplinary equity-minded data communities for undergraduate and graduate students through scholarship, collaboration, mentorship, and networking.
  
### 2. Data Accessibility Initiative
- **Objective:** Make data work accessible and relevant for both technical and non-technical majors and fields.
  
### 3. Equity Framework Exploration
- **Objective:** Explore and apply data equity frameworks to build enriching data communities based on mutual support, including anti-racist, queer, feminist, and social justice pedagogies and epistemologies.
  
### 4. Knowledge Creation
- **Objective:** Become a maker of open-sourced technical and scholarly knowledge about data by producing project deliverables, product reviews, project manuals, and scholarship.



## Join Us!

Whether you're a seasoned tech enthusiast or a novice interested in learning about data, our paid opportunities can help you build a diverse portfolio and valuable skills.

Ready to dive in? Join us in shaping the future of data at Tulane University!

[Apply Now](https://datainstitute.tulane.edu/data-lab)
